# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: BNMI 
email: anders.folkesson@gu.se
description: Welcome to BNMI 2024, Gothenburg

domain: xfolka.github.io
#baseurl:  ""
#url: https://xfolka.github.io # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  xfolka
#permalink: /:title/

cover: "/assets/header_image.jpg"
logo: /assets/bnmi.png

collections:
  abstracts:
    output: true

# Build settings
remote_theme: daviddarnes/alembic@main
#theme: centrarium
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-redirect-from

# Build settings
markdown: kramdown
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Pagination Settings
# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"
  sort_reverse: true

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/DavidDarnes
  LinkedIn: https://www.linkedin.com/in/daviddarnes
  GitHub: https://github.com/daviddarnes
  link: https://darn.es
  RSS: /feed.xml  

sharing_links:
  Twitter: "#1DA1F2"
  facebook: "#3B5998"
#  Pinterest: "#BD081C"
  LinkedIn: "#0077B5"
#  tumblr: "#36465D"
#  Reddit: "#FF4500"
#  HackerNews: "#ff6600"
#  DesignerNews: "#2D72D9"
#  Email: true

navigation_header:
- title: Home
  url: /home/
- title: Schedule
  url: /schedule/
- title: Map
  url: /map/
- title: Talks & Sessions
  url: /talks/
- title: Search
  url: /search/

navigation_footer:
- title: CCI
  url: https://www.gu.se/core-facilities/infrastruktur/centre-for-cellular-imaging-cci
- title: Contact
  url: /Contact/


fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
